//! Version-sentinel code generation (plan T2a step 8).
//!
//! pyo3 module attributes need a `&'static str` literal; `concat!`/`env!` at
//! the crate site cannot build the underscored sentinel name from the Cargo
//! version, so this script materializes `version_sentinel.rs` in OUT_DIR:
//!
//! ```text
//! CARGO_PKG_VERSION = "0.1.0"  ->  "__niu_natives_v0_1_0"
//! ```
//!
//! lib.rs `include!`s the file and registers the sentinel (plus `__version__`)
//! as module attributes, so Python can assert the native extension ABI matches
//! the expected crate version (plan A2 / T3 acceptance).

use std::{
	env,
	fs,
	path::PathBuf,
};

fn main() {
	// macOS extension modules must link with `-undefined dynamic_lookup` so the
	// Python C-API symbols resolve against the host interpreter at import time
	// (pyo3 extension-module never links libpython). pyo3-build-config emits the
	// cdylib link args; .cargo/config.toml repeats them for test binaries.
	pyo3_build_config::add_extension_module_link_args();

	let version = env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION is set by cargo");
	let sentinel = format!("__niu_natives_v{}", version.replace('.', "_"));
	let out = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set by cargo"))
		.join("version_sentinel.rs");
	fs::write(
		&out,
		format!(
			"// Generated by build.rs from CARGO_PKG_VERSION — do not edit.\n\
			 // Sentinel Python module attribute: presence proves the native extension\n\
			 // ABI matches the Python-side expectation for this crate version.\n\
			 pub const SENTINEL: &str = \"{sentinel}\";\n"
		),
	)
	.expect("failed to write version_sentinel.rs");
	println!("cargo:rerun-if-changed=build.rs");
	println!("cargo:rerun-if-env-changed=CARGO_PKG_VERSION");
}
