[package]
name = "niu-launcher"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["blocking", "json"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["time", "local-time"] }
time = { version = "0.3", features = ["macros"] }
dunce = "1"
dirs = "6"
ctrlc = "3"

iced = { version = "0.13", features = ["canvas"] }
rfd = "0.14"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal", "process"] }
